- name: "copy {{ component }} service to system directory"
  ansible.builtin.template:
    src: "{{ component }}.service.jinja2"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: Reload daemon Reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Enable and start {{ component }} service"
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted # even app is not running you can restart
    enabled: yes